// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GithubInteractor is an autogenerated mock type for the GithubInteractor type
type GithubInteractor struct {
	mock.Mock
}

// GetStarredRepositories provides a mock function with given fields: username
func (_m *GithubInteractor) GetStarredRepositories(username string) ([]byte, error) {
	ret := _m.Called(username)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRepositories provides a mock function with given fields: username
func (_m *GithubInteractor) GetUserRepositories(username string) ([]byte, error) {
	ret := _m.Called(username)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGithubInteractor interface {
	mock.TestingT
	Cleanup(func())
}

// NewGithubInteractor creates a new instance of GithubInteractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGithubInteractor(t mockConstructorTestingTNewGithubInteractor) *GithubInteractor {
	mock := &GithubInteractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
